import Canvas from "@/components/canvas/canvas"
import MainPageHeader from "@/components/editor/header"
import { AuthGuard } from "@/contexts/auth"
import EditorProvider from "@/contexts/editor"

export const metadata = {
  title: 'AI Artist Editor',
  description: 'Generated by create next app',
}

export default function EditorLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthGuard>
      <EditorProvider>
        <MainPageHeader />
        <div style={{ display: 'flex', height: 'calc(100vh - 56px)' }}>
          {children}
          <Canvas />
        </div>
      </EditorProvider>
    </AuthGuard>
  )
}
